version: "3.8"

services:

  cups:
    build: .
    image: drcoccodrillus/cups:latest
    container_name: cups
    restart: always
    privileged: true
    devices:
      - /dev:/dev
    ports:
      - "8631:631"
    networks:
      - printer-network

networks:
  printer-network:
    name: printer-network
    driver: bridge
